// ============================================================
// Mock data — Spec §6.1, §5.x
// ============================================================
import { buildGateFields, GATE_CRITERIA } from "./gate-config";
import type {
  AiRequestData,
  CriterionData,
  CurrentUser,
  DraftItem,
  GateId,
  GateReview,
  Initiative,
  NotificationItem,
} from "./types";

export const CURRENT_USER: CurrentUser = {
  name: "Dennis Aogo",
  jobTitle: "AI Governance",
  // Demo default: holds all gate roles so every gate is decidable.
  roles: [
    "REQUESTER",
    "GATE1_INTAKE",
    "GATE2_RISK",
    "GATE3_SECURITY",
    "GATE4_GOLIVE",
    "GATE5_OPERATE",
  ],
  dashboardView: "AIGOV",
};

function req(overrides: Partial<AiRequestData>): AiRequestData {
  return {
    titel: "",
    art: "Assistenz / Copilot",
    fachbereich: "",
    aiOwner: "",
    managementSponsor: "",
    problem: "",
    ergebnis: "",
    nutzen: [],
    nutzenhypothese: "",
    kiErforderlich: "Ja",
    kiBegruendung: "",
    nutzerkreis: "",
    geschaeftsprozess: "",
    erwarteteNutzung: "regelmäßig",
    datenarten: "interne Unternehmensdaten",
    datenklasse: "Klasse 1: Internal",
    entscheidungseinfluss: "unterstützend, menschliche Prüfung erforderlich",
    bevorzugteLoesung: "",
    betriebsmodell: "externes Cloud-/SaaS-Modell",
    systeme: "",
    integrationen: ["Benutzeroberfläche"],
    externerAnbieter: "",
    nutzungsvolumen: "",
    technischerAnsprechpartner: "",
    ...overrides,
  };
}

// Seed gate reviews up to (and including) the current gate.
function seedReviews(
  upToGate: GateId,
  request: AiRequestData,
  decideThrough: GateId = 0 as GateId,
): Partial<Record<GateId, GateReview>> {
  const out: Partial<Record<GateId, GateReview>> = {};
  for (let g = 1 as GateId; g <= upToGate; g = (g + 1) as GateId) {
    const fields = buildGateFields(g, request);
    // Pre-confirm fields for gates already passed (g < decideThrough).
    const confirmed = g < decideThrough;
    const criteria: CriterionData[] = GATE_CRITERIA[g].map((label) => ({
      label,
      status: confirmed ? "met" : "unchecked",
    }));
    out[g] = {
      gate: g,
      criteria,
      fields: fields.map((f) => ({
        ...f,
        decision: confirmed ? "confirmed" : "unset",
      })),
    };
  }
  return out;
}

const r1 = req({
  titel: "KI Wissens-Assistent",
  fachbereich: "Governance, DE/AT/CH",
  aiOwner: "Fabian Dietrich",
  managementSponsor: "Dr. Lena Hoffmann",
  problem:
    "Mitarbeitende finden interne Richtlinien nur schwer und verbringen viel Zeit mit Recherche.",
  ergebnis:
    "Schnelle, verlässliche Antworten auf Richtlinienfragen mit Quellenangabe.",
  nutzen: ["Zeit-/Kapazitätseinsparung", "besseres Wissensmanagement"],
  nutzenhypothese:
    "Reduktion des monatlichen Rechercheaufwands um ca. 80 Stunden.",
  nutzerkreis: "Alle Mitarbeitenden der Governance- und Compliance-Bereiche.",
  geschaeftsprozess: "Richtlinien-Recherche und interne Auskunft.",
  systeme: "DMS, SharePoint, interne Wissensbasis",
  externerAnbieter: "Microsoft Azure OpenAI",
  nutzungsvolumen: "ca. 1.500 Anfragen / Monat",
  bevorzugteLoesung: "Azure OpenAI + RAG",
  technischerAnsprechpartner: "Max Mustermann",
});

const r2 = req({
  titel: "KI Management-Assistant",
  fachbereich: "Vorstandsstab, Holding",
  aiOwner: "Sandra Kowalski",
  problem: "Management-Reports werden manuell aus vielen Quellen zusammengestellt.",
  ergebnis: "Automatisierte Entwürfe von Management-Summaries.",
  nutzen: ["Zeit-/Kapazitätseinsparung", "schnellere Bearbeitung"],
  nutzenhypothese: "Halbierung der Vorbereitungszeit für Monatsreports.",
  nutzerkreis: "Vorstand und Bereichsleitung.",
  geschaeftsprozess: "Management-Reporting.",
  systeme: "BI-Plattform, SQL, CRM",
  externerAnbieter: "noch offen",
  nutzungsvolumen: "ca. 200 Reports / Monat",
});

const r3 = req({
  titel: "KI Prompt Library",
  fachbereich: "IT / Enablement",
  aiOwner: "Tobias Renner",
  problem: "Es fehlt eine kuratierte Sammlung geprüfter Prompts.",
  ergebnis: "Zentrale, freigegebene Prompt-Bibliothek.",
  nutzen: ["Qualitätsverbesserung", "besseres Wissensmanagement"],
  nutzenhypothese: "Konsistentere Ergebnisse über Teams hinweg.",
  nutzerkreis: "Alle KI-Nutzenden.",
  geschaeftsprozess: "Prompt-Verwaltung.",
  systeme: "interne Wissensbasis",
  externerAnbieter: "intern",
  nutzungsvolumen: "ca. 500 Zugriffe / Monat",
});

const r4 = req({
  titel: "Claude Code Opus 4.8 Integration",
  art: "Agent / Automatisierung",
  fachbereich: "Software Engineering, DE",
  aiOwner: "Miriam Bauer",
  managementSponsor: "Jens Albrecht",
  problem: "Entwicklungszyklen sind durch manuelle Routinetätigkeiten verlangsamt.",
  ergebnis: "KI-gestützte Code-Erstellung und Reviews in der IDE.",
  nutzen: ["Zeit-/Kapazitätseinsparung", "Qualitätsverbesserung"],
  nutzenhypothese: "Steigerung der Entwicklerproduktivität um 25%.",
  nutzerkreis: "Entwicklungsteams.",
  geschaeftsprozess: "Softwareentwicklung.",
  datenarten: "vertrauliche Daten",
  datenklasse: "Klasse 3: Confidential",
  entscheidungseinfluss: "unterstützend, menschliche Prüfung erforderlich",
  betriebsmodell: "hybride Lösung",
  systeme: "Git-Repositories, CI/CD, interne Plattform",
  integrationen: ["API", "MCP", "automatisierter Workflow"],
  externerAnbieter: "Anthropic (Claude Opus 4.8)",
  nutzungsvolumen: "ca. 50 Entwickler täglich",
  bevorzugteLoesung: "Claude Code + MCP",
});

const r5 = req({
  titel: "GBT 5.5 Integration",
  fachbereich: "Customer Service, EU",
  aiOwner: "Paula Schäfer",
  problem: "Hohes Volumen wiederkehrender Kundenanfragen.",
  ergebnis: "Teilautomatisierte Beantwortung von Standardanfragen.",
  nutzen: ["schnellere Bearbeitung", "Vermeidung externer Kosten"],
  nutzenhypothese: "Reduktion der Bearbeitungszeit um 40%.",
  nutzerkreis: "Customer-Service-Agents.",
  geschaeftsprozess: "Kundenkommunikation.",
  systeme: "CRM, Ticketsystem",
  externerAnbieter: "OpenAI",
  nutzungsvolumen: "ca. 10.000 Anfragen / Monat",
});

export const INITIATIVES: Initiative[] = [
  {
    id: "req-123",
    registerId: "AI-REG-025",
    title: r1.titel,
    summary: "Kleine Summary über den internen Wissensassistenten.",
    description: "Interner RAG-Assistent für Richtlinien und Wissensquellen.",
    aiOwner: r1.aiOwner,
    technicalOwner: r1.technischerAnsprechpartner!,
    fachbereich: r1.fachbereich,
    risk: "Low Risk",
    dataClass: "C1 – C3",
    lifecycleLabel: "Pilot unter Auflagen",
    currentGate: 4,
    gateProgress: 75,
    status: "in_review",
    reApprovalDue: false,
    gateReviews: seedReviews(4, r1, 4),
    createdDate: "12.01.2026",
    lastChanged: "2026-06-24",
    nextReview: "15.07.2026",
    openAuflagen: 2,
    criticalFindings: 0,
    changesSinceApproval: "1 geplante Erweiterung des Nutzerkreises.",
    gateDecisionSummary: "Gate 4: Pilot für 40 Mitarbeitende freigegeben.",
    nextStep: "Gate 5 Review nach Pilotphase.",
    usage: {
      activeUsers: 32,
      pilotUsers: 40,
      calls30d: 23840,
      tokensUsedM: 8.4,
      tokenLimitM: 10,
      costMonth: 1240,
      costLimit: 2000,
    },
    request: r1,
  },
  {
    id: "req-456",
    registerId: "AI-REG-018",
    title: r2.titel,
    summary: "Automatisierte Management-Summaries aus mehreren Quellen.",
    description: "Erzeugt Entwürfe von Management-Summaries aus mehreren Quellen.",
    aiOwner: r2.aiOwner,
    technicalOwner: "Kai Berger",
    fachbereich: r2.fachbereich,
    risk: "in Prüfung",
    dataClass: "C1 – C2",
    lifecycleLabel: "In Prüfung",
    currentGate: 1,
    gateProgress: 15,
    status: "in_review",
    reApprovalDue: false,
    gateReviews: seedReviews(1, r2, 1),
    createdDate: "03.02.2026",
    lastChanged: "2026-06-26",
    nextReview: "01.09.2026",
    openAuflagen: 0,
    criticalFindings: 0,
    changesSinceApproval: "—",
    gateDecisionSummary: "Intake eingereicht, Business Case in Prüfung.",
    nextStep: "Gate 1 Entscheidung durch das Intake Board.",
    usage: {
      activeUsers: 0,
      pilotUsers: 0,
      calls30d: 0,
      tokensUsedM: 0,
      tokenLimitM: 5,
      costMonth: 0,
      costLimit: 1500,
    },
    request: r2,
  },
  {
    id: "req-789",
    registerId: "AI-REG-011",
    title: r3.titel,
    summary: "Zentrale, kuratierte Bibliothek freigegebener Prompts.",
    description: "Zentrale, kuratierte Bibliothek freigegebener Prompts.",
    aiOwner: r3.aiOwner,
    technicalOwner: "Nina Faber",
    fachbereich: r3.fachbereich,
    risk: "Low Risk",
    dataClass: "C1",
    lifecycleLabel: "In Prüfung",
    currentGate: 1,
    gateProgress: 10,
    status: "in_review",
    reApprovalDue: false,
    gateReviews: seedReviews(1, r3, 1),
    createdDate: "18.03.2026",
    lastChanged: "2026-06-20",
    nextReview: "01.10.2026",
    openAuflagen: 0,
    criticalFindings: 0,
    changesSinceApproval: "—",
    gateDecisionSummary: "Intake eingereicht.",
    nextStep: "Gate 1 Entscheidung durch das Intake Board.",
    usage: {
      activeUsers: 0,
      pilotUsers: 0,
      calls30d: 0,
      tokensUsedM: 0,
      tokenLimitM: 2,
      costMonth: 0,
      costLimit: 500,
    },
    request: r3,
  },
  {
    id: "req-321",
    registerId: "AI-REG-029",
    title: r4.titel,
    summary: "KI-gestützte Code-Erstellung und Reviews in der IDE.",
    description: "KI-gestützte Code-Erstellung und Reviews direkt in der IDE.",
    aiOwner: r4.aiOwner,
    technicalOwner: "Jonas Weber",
    fachbereich: r4.fachbereich,
    risk: "High Risk",
    dataClass: "C3",
    lifecycleLabel: "Security & Architecture Review",
    currentGate: 3,
    gateProgress: 55,
    status: "in_review",
    reApprovalDue: false,
    gateReviews: seedReviews(3, r4, 3),
    createdDate: "22.04.2026",
    lastChanged: "2026-06-27",
    nextReview: "15.08.2026",
    openAuflagen: 3,
    criticalFindings: 1,
    changesSinceApproval: "Erweiterung auf zwei weitere Teams geplant.",
    gateDecisionSummary: "Gate 2: Risikoklasse High Risk festgelegt.",
    nextStep: "Gate 3 Entscheidung durch Security & Architektur.",
    usage: {
      activeUsers: 41,
      pilotUsers: 50,
      calls30d: 61200,
      tokensUsedM: 24.6,
      tokenLimitM: 40,
      costMonth: 4820,
      costLimit: 6000,
    },
    request: r4,
  },
  {
    id: "req-654",
    registerId: "AI-REG-024",
    title: r5.titel,
    summary: "Teilautomatisierte Beantwortung von Standardanfragen.",
    description: "Teilautomatisierte Beantwortung wiederkehrender Standardanfragen.",
    aiOwner: r5.aiOwner,
    technicalOwner: "Lea Vogt",
    fachbereich: r5.fachbereich,
    risk: "Low Risk",
    dataClass: "C2",
    lifecycleLabel: "Re-Approval fällig",
    currentGate: 4,
    gateProgress: 78,
    status: "in_review",
    reApprovalDue: true,
    gateReviews: seedReviews(4, r5, 4),
    createdDate: "09.05.2026",
    lastChanged: "2026-06-28",
    nextReview: "10.07.2026",
    openAuflagen: 1,
    criticalFindings: 0,
    changesSinceApproval: "Neue Intent-Kategorien im Ticketsystem.",
    gateDecisionSummary: "Gate 4: Go-Live unter Auflagen freigegeben.",
    nextStep: "Re-Approval für Q3 fällig.",
    usage: {
      activeUsers: 58,
      pilotUsers: 60,
      calls30d: 98400,
      tokensUsedM: 31.2,
      tokenLimitM: 35,
      costMonth: 5460,
      costLimit: 6000,
    },
    request: r5,
  },
];

export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: "n1",
    type: "Alerts",
    title: "Kostenbudget zu 90% ausgeschöpft",
    initiativeName: "GBT 5.5 Integration",
    read: false,
  },
  {
    id: "n2",
    type: "Policy",
    title: "Neue DLP-Richtlinie betrifft diese Initiative",
    initiativeName: "KI Wissens-Assistent",
    read: false,
  },
  {
    id: "n3",
    type: "Incident",
    title: "Erhöhte Fehlerrate im Retrieval erkannt",
    initiativeName: "Claude Code Opus 4.8 Integration",
    read: false,
  },
  {
    id: "n4",
    type: "Re-Approval",
    title: "Re-Approval erforderlich (planmäßig)",
    initiativeName: "GBT 5.5 Integration",
    read: false,
  },
  {
    id: "n5",
    type: "New Request",
    title: "Neuer AI Request eingereicht",
    initiativeName: "KI Management-Assistant",
    read: true,
  },
  {
    id: "n6",
    type: "Policy",
    title: "Modellroute aktualisiert",
    initiativeName: "KI Prompt Library",
    read: true,
  },
];

export const DRAFTS: DraftItem[] = [
  { id: "d1", title: "KI Onboarding-Assistent", type: "New Request", completeness: 65 },
  {
    id: "d2",
    title: "GBT 5.5 Integration — Re-Approval Q3",
    type: "Re-Approval",
    completeness: 80,
    initiativeId: "req-654",
  },
  { id: "d3", title: "KI Vertragsanalyse", type: "New Request", completeness: 40 },
  {
    id: "d4",
    title: "KI Wissens-Assistent — jährliche Prüfung",
    type: "Re-Approval",
    completeness: 90,
    initiativeId: "req-123",
  },
];

export const RECENTS = [
  { id: "req-123", label: "AI Request 123" },
  { id: "req-456", label: "AI Request 456" },
  { id: "req-789", label: "AI Request 789" },
];

// Empty request data for a brand-new wizard draft.
export const EMPTY_REQUEST: AiRequestData = {
  titel: "",
  art: "",
  fachbereich: "",
  aiOwner: "",
  managementSponsor: "",
  problem: "",
  ergebnis: "",
  nutzen: [],
  nutzenhypothese: "",
  kiErforderlich: "",
  kiBegruendung: "",
  nutzerkreis: "",
  geschaeftsprozess: "",
  erwarteteNutzung: "",
  datenarten: "",
  datenklasse: "",
  entscheidungseinfluss: "",
  menschlicheKontrolle: "",
  bevorzugteLoesung: "",
  betriebsmodell: "",
  systeme: "",
  integrationen: [],
  externerAnbieter: "",
  nutzungsvolumen: "",
  technischerAnsprechpartner: "",
};
